spring:
  application:
    name: agendapro-challenge
  datasource:
      url: jdbc:mysql://localhost:33060/agendapro?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: agendapro-challenge